Check for Azure token on Ed-Fi repositories

diff --git a/.github/workflows/Instl edFi.installer.swaggerUI manual.yml b/.github/workflows/Instl edFi.installer.swaggerUI manual.yml
--- a/.github/workflows/Instl edFi.installer.swaggerUI manual.yml
+++ b/.github/workflows/Instl edFi.installer.swaggerUI manual.yml
@@ -15,6 +15,7 @@ env:
   AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
   AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
   VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   build:
@@ -23,7 +24,13 @@ jobs:
 
     steps:
     - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "Missing Azure Token" 
+        exit 1   
     - name: build
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       run: |
         .\build-package.ps1 -InformationalVersion ${{env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -NugetFeed ${{env.AZURE_ARTIFACT_URL}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }}
       shell: pwsh
diff --git a/.github/workflows/Rebuild Database Templates.yml b/.github/workflows/Rebuild Database Templates.yml
--- a/.github/workflows/Rebuild Database Templates.yml
+++ b/.github/workflows/Rebuild Database Templates.yml
@@ -30,6 +30,7 @@ env:
   REF_NAME:  ${{ GITHUB.REF_NAME }}
   REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}  
   EDFI_ODS_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   build:
@@ -37,6 +38,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check for Repo Dispatch Token
+      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.EDFI_ODS_TOKEN == '' }}
+      run: | 
+        echo "Missing GitHub Token" 
+        exit 1
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # 2.1.0
       with:
@@ -71,6 +77,7 @@ jobs:
         Write-Host "Current Branch: $current_branch"   
         echo "current_branch=$current_branch" >> $Env:GITHUB_ENV                   
     - name: Dispatch EdFi.Ods.CodeGen workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_codegen
       with:
@@ -81,6 +88,7 @@ jobs:
         workflow: Pkg EdFi.Ods.CodeGen.yml
         workflow_timeout_seconds: 4800
     - name: Await to complete the execution for EdFi.Ods.CodeGen RunID ${{ steps.return_dispatch_codegen.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -138,6 +146,7 @@ jobs:
         git push -u origin ${{ env.current_branch }}
 
     - name: Dispatch EdFi.Ods.Extensions.Homograph workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_homograph
       with:
@@ -149,6 +158,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch  EdFi.Ods.Extensions.Sample workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_sample
       with:
@@ -160,6 +170,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch  EdFi.Ods.Extensions.TPDM worflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_TPDM
       with:
@@ -171,6 +182,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Await to complete the execution for EdFi.Ods.Extensions.Homograph RunID ${{ steps.return_dispatch_homograph.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -181,6 +193,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Extensions.Sample RunID ${{ steps.return_dispatch_sample.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -191,6 +204,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Extensions.TPDM RunID ${{ steps.return_dispatch_TPDM.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -273,6 +287,7 @@ jobs:
         git push -u origin ${{ env.current_branch }}
 
     - name: Dispatch EdFi.Ods.Populated.Template  workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_populated_template
       with:
@@ -284,6 +299,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch EdFi.Ods.Populated.Template.PostgreSQL workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_populated_template_postgresql
       with:
@@ -295,6 +311,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch EdFi.Ods.Minimal.Template  workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_minimal_template
       with:
@@ -306,6 +323,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch EdFi.Ods.Minimal.Template.PostgreSQL  workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_minimal_template_postgresql
       with:
@@ -317,6 +335,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Await to complete the execution for EdFi.Ods.Minimal.Template.PostgreSQL RunID ${{ steps.return_dispatch_minimal_template_postgresql.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -327,6 +346,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Minimal.Template RunID ${{ steps.return_dispatch_minimal_template.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -337,6 +357,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Populated.Template RunID ${{ steps.return_dispatch_populated_template.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -347,6 +368,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Populated.Template.PostgreSQL RunID ${{ steps.return_dispatch_populated_template_postgresql.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -451,6 +473,7 @@ jobs:
         git push -u origin ${{ env.current_branch }}
 
     - name: Dispatch EdFi.Ods.Populated.Template.TPDM  workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_populated_template_TPDM
       with:
@@ -462,6 +485,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch EdFi.Ods.Populated.Template.TPDM.PostgreSQL workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_populated_template_TPDM_postgresql
       with:
@@ -473,6 +497,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch EdFi.Ods.Minimal.Template.TPDM  workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_minimal_template_TPDM
       with:
@@ -484,6 +509,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Dispatch EdFi.Ods.Minimal.Template.TPDM.PostgreSQL  workflow
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/return-dispatch@290d1ad3ca0a323120745aea7a44ce63ed91a982 #v1.8.0
       id: return_dispatch_minimal_template_TPDM_postgresql
       with:
@@ -495,6 +521,7 @@ jobs:
         workflow_timeout_seconds: 4800
 
     - name: Await to complete the execution for EdFi.Ods.Minimal.Template.TPDM.PostgreSQL RunID ${{ steps.return_dispatch_minimal_template_TPDM_postgresql.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -505,6 +532,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Minimal.Template.TPDM RunID ${{ steps.return_dispatch_minimal_template_TPDM.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -515,6 +543,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Populated.Template.TPDM RunID ${{ steps.return_dispatch_populated_template_TPDM.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
@@ -525,6 +554,7 @@ jobs:
         poll_interval_ms: 5000
 
     - name: Await to complete the execution for EdFi.Ods.Populated.Template.TPDM.PostgreSQL RunID ${{ steps.return_dispatch_populated_template_TPDM_postgresql.outputs.run_id }}
+      if: ${{ env.EDFI_ODS_TOKEN != '' }}
       uses: codex-/await-remote-run@d04eeb1e053a19a32037eb0b8ddee6ab4f19790a #v1.7.0
       with:
         token: ${{ env.EDFI_ODS_TOKEN }}
