Annotate error messages

diff --git a/.github/workflows/Publish to Azure Artifacts.yml b/.github/workflows/Publish to Azure Artifacts.yml
--- a/.github/workflows/Publish to Azure Artifacts.yml
+++ b/.github/workflows/Publish to Azure Artifacts.yml
@@ -29,8 +29,8 @@ jobs:
     - name: Check for Azure token
       if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
       run: | 
-        echo "Missing Azure Token" 
-          exit 1
+        echo "::error::Missing Azure Token"
+        exit 1
     - name: Download SandboxAdmin,SwaggerUI,WebApi,Databases,EdFi.Ods.Api.Sdk,EdFi.SdkGen NugetPackages
       uses: dawidd6/action-download-artifact@1cf11afe3f1874cee82a8d5a2b45c0fd63f0fa22 #v2.19.0
       with:
