Review comments codefix

diff --git a/.github/workflows/Publish to Docker Hub.yml b/.github/workflows/Publish to Docker Hub.yml
--- a/.github/workflows/Publish to Docker Hub.yml
+++ b/.github/workflows/Publish to Docker Hub.yml
@@ -85,7 +85,8 @@ jobs:
         shell: pwsh
 
   docker-publish:
-    if: needs.FindStandardAndExtensionVersions.outputs.StandardVersions != ''
+    if: (needs.FindStandardAndExtensionVersions.outputs.StandardVersions != '' &&
+        needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions != '')
     needs: FindStandardAndExtensionVersions
     runs-on: ubuntu-latest
     strategy:
@@ -94,19 +95,31 @@ jobs:
         ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
     name: Publish to Docker Hub (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }})
     steps:
+      - name: Check for Docker Hub Token
+        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.DOCKER_HUB_TOKEN == '' }}
+        run: | 
+          echo "::error::Missing Docker Hub Token"
+          exit 1   
+      - name: Exit success if Docker Hub Token is missing in forked repository
+        if: ${{ env.DOCKER_HUB_TOKEN == '' }}
+        run: |
+          echo "Skipping Publish"           
       - name: Wait 20s for Azure Artifacts caching
         run: sleep 20
 
       - name: Checkout Repository
+        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
 
       - name: Log in to Docker Hub
+        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
         with:
           username: ${{ env.DOCKER_USERNAME }}
           password: ${{ env.DOCKER_HUB_TOKEN }}
 
       - name: Build and Push
+        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         run: |
           # Note: all images will receive the same version number for this Docker release
           if ($env:github_event_name -eq "release" -and $env:github_event_action -eq "published") {
