Fail gracefully on forked repositories when docker hub token is missing

diff --git a/.github/workflows/Publish to Docker Hub.yml b/.github/workflows/Publish to Docker Hub.yml
--- a/.github/workflows/Publish to Docker Hub.yml
+++ b/.github/workflows/Publish to Docker Hub.yml
@@ -17,6 +17,7 @@ on:
 env:
   DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
   DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   docker-publish:
@@ -24,6 +25,18 @@ jobs:
     name: Publish to Docker Hub
     runs-on: ubuntu-latest
     steps:
+      - name: Check for Docker Hub Token
+        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.DOCKER_HUB_TOKEN == '' }}
+        run: | 
+          echo "::error::Missing Docker Hub Token"
+          exit 1 
+
+      - name: Exit success if Docker Hub Token is missing in forked repository
+        if: ${{ env.DOCKER_HUB_TOKEN == '' }}
+        run: |
+          echo "Skipping Publish"
+          exit 0
+
       - name: Wait 20s for Azure Artifacts caching
         run: sleep 20
 
