[ODS-5994] Fix docker pre-release and release image workflow  (#791)
* Changes to manually update docker images

* Fix issue

* fixed issue

* Fixed tag

* Add prerelease/release support

* Add prerelease flag to Docket Test action

* Review comments codefix

* Moving env.DOCKER_HUB_TOKEN != '' condtion to FindStandardAndExtensionVersions job

---------

Co-authored-by: m.semalaiappan <m.semalaiappan@gmail.com>

diff --git a/.github/workflows/Publish to Docker Hub.yml b/.github/workflows/Publish to Docker Hub.yml
--- a/.github/workflows/Publish to Docker Hub.yml
+++ b/.github/workflows/Publish to Docker Hub.yml
@@ -32,40 +32,26 @@ jobs:
       StandardVersions: ${{ steps.Set_StandardVersions.outputs.StandardVersions }}
       ExtensionVersions: ${{ steps.Set_ExtensionVersions.outputs.ExtensionVersions }}
     steps:
-      - name: Check for Docker Hub Token
-        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.DOCKER_HUB_TOKEN == '' }}
-        run: | 
-          echo "::error::Missing Docker Hub Token"
-          exit 1
-
-      - name: Exit success if Docker Hub Token is missing in forked repository
-        if: ${{ env.DOCKER_HUB_TOKEN == '' }}
-        run: |
-          echo "Skipping Publish"
-      
+    
       - name: Checkout Ed-Fi-ODS
-        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
         with:
           repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
           path: Ed-Fi-ODS/
 
       - name: Checkout Ed-Fi-Extensions
-        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
         with:
             repository: Ed-Fi-Alliance-OSS/Ed-Fi-Extensions
             path: Ed-Fi-Extensions/
 
       - name: Is pull request branch exists in Ed-Fi-Extensions
-        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         working-directory: ./Ed-Fi-ODS/
         shell: pwsh
         run: |
           .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-Extensions"
 
       - name: Set StandardVersions
-        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         id: Set_StandardVersions
         working-directory: ./Ed-Fi-ODS/
         run: |
@@ -75,7 +61,6 @@ jobs:
         shell: pwsh
 
       - name: Set ExtensionVersions
-        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         id: Set_ExtensionVersions
         working-directory: ./Ed-Fi-Extensions/
         run: |
@@ -85,7 +70,8 @@ jobs:
         shell: pwsh
 
   docker-publish:
-    if: ${{ always() && env.DOCKER_HUB_TOKEN != '' }}
+    if: (needs.FindStandardAndExtensionVersions.outputs.StandardVersions != '' &&
+        needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions != '')
     needs: FindStandardAndExtensionVersions
     runs-on: ubuntu-latest
     strategy:
@@ -94,30 +80,42 @@ jobs:
         ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
     name: Publish to Docker Hub (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }})
     steps:
+      - name: Check for Docker Hub Token
+        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.DOCKER_HUB_TOKEN == '' }}
+        run: | 
+          echo "::error::Missing Docker Hub Token"
+          exit 1   
+      - name: Exit success if Docker Hub Token is missing in forked repository
+        if: ${{ env.DOCKER_HUB_TOKEN == '' }}
+        run: |
+          echo "Skipping Publish"           
       - name: Wait 20s for Azure Artifacts caching
         run: sleep 20
 
       - name: Checkout Repository
+        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
 
       - name: Log in to Docker Hub
+        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
         with:
           username: ${{ env.DOCKER_USERNAME }}
           password: ${{ env.DOCKER_HUB_TOKEN }}
 
       - name: Build and Push
+        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
         run: |
-          ./get-versions.ps1 -PackageVersion ${{ env.PACKAGE_VERSION }} -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }}
-
           # Note: all images will receive the same version number for this Docker release
           if ($env:github_event_name -eq "release" -and $env:github_event_action -eq "published") {
+            ./get-versions.ps1 -PackageVersion ${{ env.PACKAGE_VERSION }} -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }}
             ./build-images.ps1 -Push -PackageVersion ${{ env.PACKAGE_VERSION }} -Patch ${{ github.run_number }}
             Write-Host "This step is triggered by a published release."
           }
           else
           {
-           ./build-images.ps1 -Push -PackageVersion ${{ env.PACKAGE_VERSION }} -Patch ${{ github.run_number }} -PreRelease
+            ./get-versions.ps1 -PackageVersion ${{ env.PACKAGE_VERSION }} -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }} -PreRelease
+            ./build-images.ps1 -Push -PackageVersion ${{ env.PACKAGE_VERSION }} -Patch ${{ github.run_number }} -PreRelease
           }
         working-directory: Docker
         shell: pwsh
